#!/usr/bin/env python3

from sys import argv
from math import sqrt

if len(argv) == 2:
	factor_list(open_read_file(argv[1]))


def open_read_file(file_name):
	with open(file_name, "r", encoding="utf-8") as file:
		lines = file.readlines()
	number_to_factor = []
	for line in lines:
		number_to_factor.append(int(line))
	return number_to_factor


def factor_list(ls):
	for i in ls:
		for k in range(1, i):
			if i == ((i // k) * k):
				print("{}={}*{}".format(i, (i // k), k))
				break
