#!/usr/bin/env python

import sys
import time

def factorize(n):
    i = 2
    while i * i <= n:
        if n % i:
            i += 1
        else:
            return i, n // i
    return n, 1

def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    input_file = sys.argv[1]

    with open(input_file, 'r') as file:
        for line in file:
            n = int(line.strip())
            p, q = factorize(n)
            print(f"{n}={p}*{q}")

if __name__ == "__main__":
    start_time = time.time()
    main()
    end_time = time.time()
    elapsed_time = end_time - start_time
    print("\nElapsed Time:", elapsed_time, "seconds")

