#!/usr/bin/env python3

from sympy import factorint
import sys

def factorize(num):
    factors = factorint(num)
    print(f"{num}={'*'.join([f'{k}**{v}' if v > 1 else str(k) for k, v in factors.items()])}")

def factor_list(filename):
    with open(filename, "r", encoding="utf-8") as file:
        numbers = [int(line) for line in file]

    for num in numbers:
        factorize(num)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)

    factor_list(sys.argv[1])

