#!/usr/bin/env python3
""" RSA Factoring Challenge """
from sys import argv
from math import isqrt

def open_read_file(file_name):
    """read from file
    add to array
    """
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
    number_to_factor = []
    for line in lines:
        number_to_factor.append(int(line))
    return number_to_factor

def factorize(n):
    """ Prime factorization of n """
    factors = []
    
    while n % 2 == 0:
        factors.append(2)
        n //= 2

    for i in range(3, isqrt(n) + 1, 2):
        while n % i == 0:
            factors.append(i)
            n //= i

    if n > 2:
        factors.append(n)

    return factors

def rsa_factorization(numbers):
    """ Factorize each number using RSA approach """
    for num in numbers:
        factors = factorize(num)
        p, q = factors[1], factors[0]
        print(f"{num}={p}*{q}")

if len(argv) == 2:
    rsa_factorization(open_read_file(argv[1]))

